name: Testing

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  test_js:
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_BROWSERS_PATH: 0

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0

    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 24

    - name: Cache multiple paths
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install package dependencies
      run: npm ci

    - name: Check for the presence of changed files inside ./change
      run: npm run checkchange
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Check Biome formatting
      run: npm run check

    - name: Run build script tests
      run: npm run test:scripts

    - name: Build workspaces
      run: npx lage build ${{ github.event_name == 'pull_request' && format('--since origin/{0}', github.event.pull_request.base.ref) || '' }} --allow-no-target-runs --verbose

    - name: Install playwright dependencies and browsers
      run: |
        npx playwright install --with-deps

    - name: Testing
      run: npx lage test:ci ${{ github.event_name == 'pull_request' && format('--since origin/{0}', github.event.pull_request.base.ref) || '' }} --allow-no-target-runs --verbose
